// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/account/v1alpha1/auth.proto

package account

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AuthenticationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthenticationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthenticationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthenticationRequestMultiError, or nil if none found.
func (m *AuthenticationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthenticationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Password

	switch v := m.AuthType.(type) {
	case *AuthenticationRequest_Email:
		if v == nil {
			err := AuthenticationRequestValidationError{
				field:  "AuthType",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Email
	case *AuthenticationRequest_Username:
		if v == nil {
			err := AuthenticationRequestValidationError{
				field:  "AuthType",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Username
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return AuthenticationRequestMultiError(errors)
	}

	return nil
}

// AuthenticationRequestMultiError is an error wrapping multiple validation
// errors returned by AuthenticationRequest.ValidateAll() if the designated
// constraints aren't met.
type AuthenticationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthenticationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthenticationRequestMultiError) AllErrors() []error { return m }

// AuthenticationRequestValidationError is the validation error returned by
// AuthenticationRequest.Validate if the designated constraints aren't met.
type AuthenticationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthenticationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthenticationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthenticationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthenticationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthenticationRequestValidationError) ErrorName() string {
	return "AuthenticationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuthenticationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthenticationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthenticationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthenticationRequestValidationError{}

// Validate checks the field values on AuthenticationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthenticationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthenticationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthenticationResponseMultiError, or nil if none found.
func (m *AuthenticationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthenticationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AuthorizationToken

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthenticationResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthenticationResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthenticationResponseValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AuthenticationResponseMultiError(errors)
	}

	return nil
}

// AuthenticationResponseMultiError is an error wrapping multiple validation
// errors returned by AuthenticationResponse.ValidateAll() if the designated
// constraints aren't met.
type AuthenticationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthenticationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthenticationResponseMultiError) AllErrors() []error { return m }

// AuthenticationResponseValidationError is the validation error returned by
// AuthenticationResponse.Validate if the designated constraints aren't met.
type AuthenticationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthenticationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthenticationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthenticationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthenticationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthenticationResponseValidationError) ErrorName() string {
	return "AuthenticationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthenticationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthenticationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthenticationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthenticationResponseValidationError{}
